"""Taichi GGUI buffer wrappers for meshes, point sets and line sets.

These classes own Taichi fields (GPU buffers) and know how to issue draw
calls on a ``ti.ui.Scene``. They carry *no* physics and are re-used by the
finger mesh, force arrows, objects, contact markers and camera frustums.

Notes on Taichi GGUI (1.7.x)
----------------------------
* Vertex data must be ``ti.Vector.field(3, ti.f32)``; GGUI caches a VBO per
  field object, so we allocate buffers once (with a capacity) and update
  their contents with ``from_numpy``.
* Triangle/line index buffers may be Taichi ``ti.i32`` fields or contiguous
  NumPy ``int32`` arrays. Mesh normals are generated by a Taichi kernel that
  needs field indices, so meshes use fields; lines use NumPy for cheapness.
* Draw calls accept ``vertex_count`` / ``index_count`` so capacity buffers
  can be partially drawn.
"""

from __future__ import annotations

import numpy as np
import taichi as ti


def _f32_3(arr: np.ndarray) -> np.ndarray:
    return np.ascontiguousarray(np.asarray(arr, dtype=np.float32).reshape(-1, 3))


class IndexedMeshBuffers:
    """Fixed-topology surface mesh with several vertex-position sets.

    Used for the finger: same triangles/edges, but positions differ between
    the undeformed and the (amplified) deformed configuration. The ``*_wire``
    sets hold the same positions pushed slightly outward along the vertex
    normals so wireframe lines do not z-fight with the surface.
    """

    def __init__(
        self,
        n_nodes: int,
        surface_faces: np.ndarray,
        surface_edges: np.ndarray | None = None,
        tet_edges: np.ndarray | None = None,
        outline_edges: np.ndarray | None = None,
        position_sets: tuple[str, ...] = ("original", "display", "original_wire", "display_wire"),
    ) -> None:
        self.n_nodes = int(n_nodes)
        # GGUI's `lines` complains about odd vertex counts even when indices are
        # used, so buffers are padded to an even length (padding = last node).
        self.n_alloc = self.n_nodes + (self.n_nodes % 2)
        self.positions: dict[str, ti.Field] = {
            name: ti.Vector.field(3, dtype=ti.f32, shape=self.n_alloc) for name in position_sets
        }
        self.colors = ti.Vector.field(3, dtype=ti.f32, shape=self.n_alloc)
        self.colors.fill(0.6)

        faces = np.ascontiguousarray(np.asarray(surface_faces, dtype=np.int32).reshape(-1))
        self.n_faces = len(faces) // 3
        self.face_indices = ti.field(dtype=ti.i32, shape=max(len(faces), 3))
        if len(faces):
            self.face_indices.from_numpy(faces)

        self.surface_edge_indices = self._edge_array(surface_edges)
        self.tet_edge_indices = self._edge_array(tet_edges)
        self.outline_edge_indices = self._edge_array(outline_edges)

    @staticmethod
    def _edge_array(edges) -> np.ndarray | None:
        if edges is None or len(edges) == 0:
            return None
        return np.ascontiguousarray(np.asarray(edges, dtype=np.int32).reshape(-1))

    # ------------------------------------------------------------ updates
    def _padded(self, arr: np.ndarray) -> np.ndarray:
        a = _f32_3(arr)
        if a.shape[0] != self.n_nodes:
            raise ValueError(f"expected {self.n_nodes} rows, got {a.shape[0]}")
        if self.n_alloc == self.n_nodes:
            return a
        return np.concatenate([a, a[-1:]], axis=0)

    def set_positions(self, name: str, xyz: np.ndarray) -> None:
        self.positions[name].from_numpy(self._padded(xyz))

    def set_colors(self, rgb: np.ndarray) -> None:
        self.colors.from_numpy(self._padded(rgb))

    def fill_colors(self, rgb) -> None:
        self.colors.from_numpy(np.tile(np.asarray(rgb, np.float32), (self.n_alloc, 1)))

    # ------------------------------------------------------------ drawing
    def draw_surface(self, scene, which: str, color=None, per_vertex_color: bool = False, wireframe: bool = False) -> None:
        if self.n_faces == 0:
            return
        scene.mesh(
            self.positions[which],
            indices=self.face_indices,
            color=tuple(color) if color is not None else (0.6, 0.6, 0.6),
            per_vertex_color=self.colors if per_vertex_color else None,
            two_sided=True,
            index_count=3 * self.n_faces,
            show_wireframe=wireframe,
        )

    def draw_surface_edges(self, scene, which: str, color, width: float) -> None:
        if self.surface_edge_indices is None:
            return
        scene.lines(self.positions[which], width=width, indices=self.surface_edge_indices, color=tuple(color))

    def draw_tet_edges(self, scene, which: str, color, width: float) -> None:
        if self.tet_edge_indices is None:
            return
        scene.lines(self.positions[which], width=width, indices=self.tet_edge_indices, color=tuple(color))

    def draw_outline(self, scene, which: str, color, width: float) -> None:
        if self.outline_edge_indices is None:
            return
        scene.lines(self.positions[which], width=width, indices=self.outline_edge_indices, color=tuple(color))

    def draw_nodes(self, scene, which: str, radius: float, color=None, per_vertex_color: bool = False) -> None:
        scene.particles(
            self.positions[which],
            radius=float(radius),
            color=tuple(color) if color is not None else (0.5, 0.5, 0.5),
            per_vertex_color=self.colors if per_vertex_color else None,
            index_count=self.n_nodes,
        )


class TriangleSoupBuffers:
    """Growable buffer of unindexed triangles with per-vertex colors.

    Used for geometry that changes shape every frame (force arrows) or is
    small and arbitrary (object primitives). ``set(vertices, colors)`` uploads
    ``(3T, 3)`` arrays in triangle order.

    ``fixed_draw=True`` makes every draw call submit the *whole* capacity with
    unused triangles parked far outside any sensible view frustum. GGUI
    re-creates a cached renderable's Vulkan buffers whenever the submitted
    vertex count changes between frames, which corrupts other renderables of
    the same frame on some drivers (blank offscreen images after the first
    frame). Offscreen renderers whose layers vary per sample use this mode.
    """

    FAR = 1.0e6  # parking position for unused capacity (outside every far plane)

    def __init__(self, capacity_triangles: int = 2048, fixed_draw: bool = False) -> None:
        self.capacity = 0
        self.count = 0  # number of *vertices* currently valid
        self.fixed_draw = bool(fixed_draw)
        self.vertices: ti.Field | None = None
        self.colors: ti.Field | None = None
        self._ensure_capacity(capacity_triangles)
        self.clear()

    def _ensure_capacity(self, n_triangles: int) -> None:
        if n_triangles <= self.capacity:
            return
        cap = max(n_triangles, 2 * self.capacity, 64)
        self.vertices = ti.Vector.field(3, dtype=ti.f32, shape=3 * cap)
        self.colors = ti.Vector.field(3, dtype=ti.f32, shape=3 * cap)
        self.capacity = cap

    def _upload(self, v: np.ndarray, c: np.ndarray) -> None:
        n_vert = len(v)
        buf_v = np.full((3 * self.capacity, 3), self.FAR, dtype=np.float32)
        buf_c = np.zeros((3 * self.capacity, 3), dtype=np.float32)
        buf_v[:n_vert] = v
        buf_c[:n_vert] = c
        # Unused capacity: a tiny, finite, far-away triangle (never degenerate,
        # so the normal kernel does not produce NaNs; never inside the frustum).
        pad = buf_v[n_vert:]
        pad[1::3, 0] += 1.0
        pad[2::3, 1] += 1.0
        self.vertices.from_numpy(buf_v)
        self.colors.from_numpy(buf_c)
        self.count = n_vert

    def set(self, vertices: np.ndarray, colors: np.ndarray) -> None:
        v = _f32_3(vertices)
        c = _f32_3(colors)
        if v.shape != c.shape:
            raise ValueError("vertices and colors must both be (3T, 3)")
        n_tri = len(v) // 3
        self._ensure_capacity(n_tri)
        self._upload(v[: 3 * n_tri], c[: 3 * n_tri])

    def clear(self) -> None:
        if self.fixed_draw:
            self._upload(np.zeros((0, 3), np.float32), np.zeros((0, 3), np.float32))
        self.count = 0

    def draw(self, scene, two_sided: bool = False, wireframe: bool = False) -> None:
        n = 3 * self.capacity if self.fixed_draw else self.count
        if n == 0:
            return
        scene.mesh(
            self.vertices,
            per_vertex_color=self.colors,
            two_sided=two_sided,
            vertex_count=n,
            show_wireframe=wireframe,
        )


class PointBuffers:
    """Growable buffer of points drawn as spheres (``scene.particles``).

    ``fixed_draw`` has the same meaning as for :class:`TriangleSoupBuffers`:
    always submit the full capacity, unused points parked far away.
    """

    FAR = TriangleSoupBuffers.FAR

    def __init__(self, capacity: int = 256, fixed_draw: bool = False) -> None:
        self.capacity = 0
        self.count = 0
        self.fixed_draw = bool(fixed_draw)
        self.centers: ti.Field | None = None
        self.colors: ti.Field | None = None
        self._ensure_capacity(capacity)
        self.clear()

    def _ensure_capacity(self, n: int) -> None:
        if n <= self.capacity:
            return
        cap = max(n, 2 * self.capacity, 16)
        self.centers = ti.Vector.field(3, dtype=ti.f32, shape=cap)
        self.colors = ti.Vector.field(3, dtype=ti.f32, shape=cap)
        self.capacity = cap

    def set(self, points: np.ndarray, colors: np.ndarray | None = None, color=None) -> None:
        p = _f32_3(points) if len(points) else np.zeros((0, 3), np.float32)
        n = len(p)
        self._ensure_capacity(n)
        buf = np.full((self.capacity, 3), self.FAR, dtype=np.float32)
        buf[:n] = p
        self.centers.from_numpy(buf)
        cbuf = np.zeros((self.capacity, 3), dtype=np.float32)
        if colors is not None:
            cbuf[:n] = _f32_3(colors)
        elif color is not None:
            cbuf[:n] = np.asarray(color, np.float32)
        self.colors.from_numpy(cbuf)
        self.count = n

    def clear(self) -> None:
        if self.fixed_draw:
            self.set(np.zeros((0, 3), np.float32))
        self.count = 0

    def draw(self, scene, radius: float) -> None:
        n = self.capacity if self.fixed_draw else self.count
        if n == 0:
            return
        scene.particles(self.centers, radius=float(radius), per_vertex_color=self.colors, index_count=n)


class LineBuffers:
    """Growable buffer of line segments given as ``(2S, 3)`` vertex pairs."""

    def __init__(self, capacity_segments: int = 256) -> None:
        self.capacity = 0
        self.count = 0
        self.vertices: ti.Field | None = None
        self.colors: ti.Field | None = None
        self._ensure_capacity(capacity_segments)

    def _ensure_capacity(self, n_segments: int) -> None:
        if n_segments <= self.capacity:
            return
        cap = max(n_segments, 2 * self.capacity, 16)
        self.vertices = ti.Vector.field(3, dtype=ti.f32, shape=2 * cap)
        self.colors = ti.Vector.field(3, dtype=ti.f32, shape=2 * cap)
        self.capacity = cap

    def set(self, segment_vertices: np.ndarray, colors: np.ndarray | None = None, color=None) -> None:
        v = _f32_3(segment_vertices) if len(segment_vertices) else np.zeros((0, 3), np.float32)
        n_seg = len(v) // 2
        self._ensure_capacity(n_seg)
        buf = np.zeros((2 * self.capacity, 3), dtype=np.float32)
        buf[: 2 * n_seg] = v[: 2 * n_seg]
        self.vertices.from_numpy(buf)
        cbuf = np.zeros((2 * self.capacity, 3), dtype=np.float32)
        if colors is not None:
            cbuf[: 2 * n_seg] = _f32_3(colors)[: 2 * n_seg]
        elif color is not None:
            cbuf[: 2 * n_seg] = np.asarray(color, np.float32)
        self.colors.from_numpy(cbuf)
        self.count = 2 * n_seg

    def draw(self, scene, width: float) -> None:
        if self.count == 0:
            return
        scene.lines(self.vertices, width=float(width), per_vertex_color=self.colors, vertex_count=self.count)


def segments_from_edges(vertices: np.ndarray, edges: np.ndarray) -> np.ndarray:
    """Expand ``(V,3)`` + ``(E,2)`` into ``(2E, 3)`` line-pair vertices."""
    v = np.asarray(vertices, dtype=float)
    e = np.asarray(edges, dtype=np.int64)
    return v[e.reshape(-1)]
